#this will build a java project with maven
name: Java CI with Maven on linux
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest	
    name: Build with Java on ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: corretto
    - name: Cache m2 folder
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2
        key: m2-${{hashFiles('**/pom.xml', '**/*.yaml')}}
        restore-keys: m2-
    - name: Build with Maven
      run: >
        xvfb-run mvn clean verify 
        surefire-report:report-only site:site
        -Pjacoco sonar:sonar
        -Dsonar.organization=nicgalli
        -Dsonar.host.url=https://sonarcloud.io
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
		GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Archive Junit Report
      uses: actions/upload-artifact@v4
      with:
        name: surefire-report-ubuntu-latest
        path: '**/target/site'